
get_data:
    data: "data/data.csv"    

data_analysis:
    data: "data/data.csv"    
    
    dataset_balance:
        title: "Deposit Distribution of Bank Customers"
        xlabel: "Deposit"
        ylabel: "Total Customers"
            

prepare_data:
    data: "data/clean_data.csv"
    
split_data:
    data: "data/prepared_data.csv"
    train_data: "data/train_data.csv"
    train_labels: "data/train_labels.csv"
    test_data: "data/test_data.csv"
    test_labels: "data/test_labels.csv"
    
model_data:
    train_data: "data/train_data.csv"
    train_labels: "data/train_labels.csv"
    test_data: "data/test_data.csv"
    test_labels: "data/test_labels.csv"
    
    nn:
        epochs: 25
        batch_size: 32
        nn_performance: "visualizations/nn_performance.png" 

    feature_importance:
        xlabel: "Feature Labels"
        ylabel: "Feature Importances"
        title: "Comparison of Different Feature Importances"
        
    rfc_params: 
        n_estimators: 100
        min_samples_split: 2 
        min_samples_leaf : 1 
        max_features : "auto"