name: run
on: [push]

jobs: 
  run-project:
    runs-on: ubuntu-latest
    container: docker://ghcr.io/iterative/cml:0-dvc2-base1
    
    steps:
      - uses: actions/checkout@v2
      - uses: iterative/setup-cml@v1
      
      - name: install requirements
        run: pip install -r requirements.txt
        
      - name: run project --1. get data
        run: python3 src/get_data.py
        
      - name: 2. analyze data
        run: python3 src/data_analysis.py
        
      - name: 3. prepare data
        run: python3 src/prepare_data.py
        
      - name: 4- split data
        run: python3 src/split_data.py
        
      - name: 5- model data
        run: python3 src/model_data.py
